version: '3'

services:
  ruby_db:
    image: mysql:5.7
    volumes:
      - ./mysql/volumes:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rails_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: passwordX

  ruby_web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home
    ports:
      - "3000:3000"
    depends_on:
      - ruby_db
    environment:
      TZ: "Asia/Tokyo"
volumes:
  bundle:
  mysql_data:

